apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  labels:
    app: demo-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-node-app
  template:
    metadata:
      labels:
        app: demo-node-app
    spec:
      containers:
      - name: node-app-demo-container
        image: rohan2567/node-app-demo:latest
		    imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
  name: node-app-svc
  labels:
    app: demo-node-app
spec:
  selector:
    app: demo-node-app
  type: NodePort
  ports:
  - nodePort: 31113
    port: 3000
    targetPort: 3000
