---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-demo
  template:
    metadata:
      labels:
        app: node-app-demo
    spec:
      containers:
      - name: node-app-container
        image: rohan2567/node-app-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
  name: demo-node-svc
  labels:
    app: node-app-demo
spec:
  selector:
    app: node-app-demo
  type: NodePort
  ports:
  - nodePort: 31113
    port: 3000
    targetPort: 3000
