apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  labels:
    app: demo-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-node-app
  template:
    metadata:
      labels:
        app: demo-node-app
    spec:
      containers:
      - name: node-app-demo-container
        image: rohan2567/node-app-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

